auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [
  path('login/', views.Login.as_view()),
  path('logout/', views.Logout.as_view()),
  path('signup/', views.Signup.as_view())
]

foxy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('social.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path

from social import views

urlpatterns = [
  path('home/', views.Home.as_view()),
  path('post/', views.Post.as_view()),
  path('post/<int:pk>/like', views.PostLike.as_view()),
  path('post/<int:pk>/comment', views.PostComment.as_view()),
  path('', views.Wall.as_view())
]

social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now=True)
  content = models.TextField()
  image = models.ImageField(blank = True)

  def __str__(self):
    return self.content[:50]

class Like(models.Model):
  post = models.ForeignKey('Post', on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
  post = models.ForeignKey('Post', on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  content = models.CharField(max_length = 1024)

class Friends(models.Model):
  person1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='person1')
  person2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='person2')

social/forms.py
from django import forms

from social import models

class PostForm(forms.ModelForm):
  class Meta:
    model = models.Post
    fields = ['content', 'image']

class PostComment(forms.ModelForm):
  class Meta:
    model = models.Comment
    fields = ['content']

social/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from social import models, forms

# Create your views here.
class Wall(LoginRequiredMixin, ListView):
  context_object_name = 'posts'
  template_name = 'social/wall.html'
  login_url = 'auth/login'

  def get_queryset(self):
    friendIds = [ friend.person2.id for friend in  models.Friends.objects.filter(person1 = self.request.user) ]
    friendIds = friendIds + [ friend.person1.id for friend in  models.Friends.objects.filter(person2 = self.request.user) ]

    return models.Post.objects.filter(user__in = friendIds).order_by('-created_at')

class Home(LoginRequiredMixin, ListView):
  context_object_name = 'posts'
  template_name = 'social/home.html'
  login_url = 'auth/login'

  def get_queryset(self):
    return models.Post.objects.filter(user = self.request.user)
  
  def get_context_data(self, *args, **kwargs):
    data = super().get_context_data(*args, **kwargs)
    data['post_form'] = forms.PostForm()

    return data

class Post(View):
  def post(self, request):
    form = forms.PostForm(request.POST, request.FILES)
    if form.is_valid():
      post = form.save(commit=False)
      post.user = request.user
      post.save()
    
    return redirect('/home/')

class PostLike(View):
  model = models.Post

  def post(self, request, pk):
    post = self.model.objects.get(pk = pk)
    models.Like.objects.create(post = post, user = request.user)
    return HttpResponse(code = 204)

class PostComment(View):
  model = models.Post
  form = forms.PostComment

  def post(self, request, pk):
    post = self.model.objects.get(pk = pk)
    form = self.form(request.POST)

    if form.is_valid():
      comment = form.save(commit = False)
      comment.post = post
      comment.user = request.user
      comment.save()
      return HttpResponse(code = 204)
    
    print(form.errors)
    return HttpResponse('Error')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foxy</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    {% block head %} {% endblock %}
  </head>
  <body>
    <nav style="margin-bottom: 1.5rem;">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Foxy</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
            <li><a href="/home">Hello, {{ user.first_name }} {{ user.last_name }}</a></li>
            <li><a href="/auth/logout">Logout</a></li>
          {% else %}
            <li><a href="/auth/login">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock %}

    {% block footer %} {% endblock %}
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="/static/social/social.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.modal');
          var instances = M.Modal.init(elems, {});
        });
    </script>
  </body>
</html>

templates/social/components/post.html
<div class="card">
  <div class="card-image">
    {% if post.image %}
      <img src="/media/{{ post.image }}" style="width:25%">
    {% endif %}
  </div>
  <div class="card-content">
    <span class="card-title">{{ post.user.first_name }} {{ post.user.last_name }}</span>
    <span>{{ post.created_at }}</span>
    <p>
      {{ post.content }}
    </p>
  </div>
  <div class="card-action">
    <a href="#" onclick="likePost({{post.id}})">{{ post.like_set.count }} Likes</a>
    <a class="modal-trigger" href="#postModal{{post.id}}">{{ post.comment_set.count }} Comments</a>
  </div>
</div>

<div id="postModal{{post.id}}" class="modal">
  <div class="modal-content">
    <h4>Comments</h4>
    <ul>
      {% for comment in post.comment_set.all %}
        <li>{{ comment.user.first_name }} - {{ comment.content }}</li>
      {% endfor %}
    </ul>
    <form onsubmit="commentPost({{post.id}}, document.getElementById('comment{{post.id}}').value);">
      <div class="input-field">
        <input id="comment{{post.id}}" type="text" class="validate">
        <label for="comment{{post.id}}">Comment</label>
        <button type="submit" class="btn waves-effect">Submit</button>
      </div>
    </form>
  </div>
</div>

templates/social/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3>Home</h3>
    <form action="/post/" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ post_form }}

      <button type="submit" class="btn waves-effect">Post</button>
    </form>
    {% for post in posts %}
      <div class="row">
        <div class="col s12">
          {% include 'social/components/post.html' %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/social/wall.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3>Wall</h3>
    {% for post in posts %}
      <div class="row">
        <div class="col s12">
          {% include 'social/components/post.html' %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}